### ISSUE TITLE
Make CFBundleIdentifier configurable.

### ISSUE THREAD

**Issue by huxi** [crotwell/gradle-macappbundle#29]
`CFBundleIdentifier` is currently [hardcoded to `mainClassName`](https://github.com/crotwell/gradle-macappbundle/blob/master/src/main/groovy/edu/sc/seis/gradle/macAppBundle/GenerateInfoPlistTask.groovy#L55).

I'd suggest to add a `bundleIdentifier` property to [`MacAppBundlePluginExtension`](https://github.com/crotwell/gradle-macappbundle/blob/master/src/main/groovy/edu/sc/seis/gradle/macAppBundle/MacAppBundlePluginExtension.groovy) and use that if configured, with `mainClassName` being the fallback.

**Comment by crotwell** [comment]
Sounds reasonable. Using mainClassName was to be compatible with the Gradle Application plugin
https://docs.gradle.org/current/userguide/application_plugin.html

**Comment by huxi** [comment]
It's definitely a reasonable default.

**Comment by crotwell** [comment]
Done in 2.1.1

**Comment by huxi** [comment]
Great! Thanks!
