### ISSUE TITLE
Configuration instructions has dead link to MacAppBundlePluginExtension

### ISSUE THREAD

**Issue by Thunderforge** [crotwell/gradle-macappbundle#32]
The [Configuration section](https://github.com/crotwell/gradle-macappbundle/wiki/Intro#configuration) of the Intro page has a link to MacAppBundlePluginExtension at https://github.com/crotwell/gradle-macappbundle/source/browse/src/main/groovy/edu/sc/seis/gradle/macAppBundle/MacAppBundlePluginExtension.groovy . However, this results in a 404 error.

I believe that it is intending to point to https://github.com/crotwell/gradle-macappbundle/blob/master/src/main/groovy/edu/sc/seis/macAppBundle/MacAppBundlePluginExtension.groovy

**Comment by crotwell** [comment]
Fixed, thanks.
