### ISSUE TITLE
How to configure what gets copied to Java directory?

### ISSUE THREAD

**Issue by chrisvire** [crotwell/gradle-macappbundle#35]
Hello,

I have a build.gradle that probably isn't standard (it works, but I am fairly new to gradle).  My app generates Android and iOS apps from a library of content.  So it has a lot of related resources needed for it.

So I have a whole directory structure that needs to copied to the Java directory.  The code expects these resources to be together:

/bin/scripture-app-builder.jar
/bin/lib/x86_64/*.dylib
/fonts/* (custom fonts)
/html/* (template html files)
/images/icons/*
/info/* (localization strings)
/ios/* (template iOS App)
/lib/* (android libraries)
/tools/* (related tools needed for building android app -- gradle, maven)

How do I override what gets copied to the Java directory?  The only thing that is getting copied now is "release.jar" and I don't think it is the correct thing.

Thanks,
Chris

**Comment by crotwell** [comment]
Couple of options, you might find it is better to treat all of these as resources to be packaged in your app's jar. You can do this by simply placing them in the src/main/resources dir in your gradle build. Gradle will put them in the jar and then they will be included with your app. This is probably the safest and most "gradle" way to do it. You can read about resource in the "Source Sets" and project layout in the Java section of the gradle docs:
https://docs.gradle.org/current/userguide/java_plugin.html

However, if you really want to just copy the files, there is nothing wrong with creating a task to do the copy into build/macapp/<projectname>.app/Contents/Java. See the docs on gradle's copy task here:
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Copy.html
You would then want to make the createApp task depend on your copy task so it is executed in the right order.
