### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by bmuschko** [crotwell/gradle-macappbundle#36]
I am using this plugin with Java 7. However, it seems like your plugin has been compiled with Java 8. I get the following error message:

    java.lang.UnsupportedClassVersionError: edu/sc/seis/macAppBundle/MacBundlePlugin: Unsupported major.minor version 52.0

Would you mind producing a new version of the plugin by setting the source and target compatibility in your `build.gradle` file so it can be used with Java 7?

    sourceCompatibility = 1.7
    targetCompatibility = 1.7

**Comment by crotwell** [comment]
Done, will upload new version shortly.
