### ISSUE TITLE
Providing external dictionary file instead of generating it

### ISSUE THREAD

**Issue by bmuschko** [crotwell/gradle-macappbundle#38]
One of my projects already provides the `Info.plist` file as a static resource. Instead of generating it, would it be possible to expose a property in the extension that can be assigned by the user and bypasses the dictionary file generation?

**Comment by crotwell** [comment]
Humm, do you mean to just copy, or to merge the generated content with extra stuff in a file? The first would be easy, but would mean you lose having the classpath generated from the buildfile. The second seems messy coding, but might be possible. Do you have interest in coding it and submitting a pull request?

If you just want to copy/overwrite, you could just set up a copy task to replace the generated Info.plist after the fact. Just set up your copy task to depend on generatePlist and have createApp depend on your copy task.

**Comment by ankits** [comment]
Turns out, I didn't need the `Info.plist`. The plugin works great so far!

**Comment by crotwell** [comment]
OK, thanks for letting me know.
