### ISSUE TITLE
Error: execCommand == null

### ISSUE THREAD

**Issue by robvadai** [crotwell/gradle-macappbundle#47]
When running `./gradlew clean build -p mymodule`

I'm getting
```
* What went wrong:
Execution failed for task ':mymodule:createDmg'.
> execCommand == null!
```

I'm using Gradle 3.3 and 2.1.6 of this plugin.

**Comment by crotwell** [comment]
Without some more information to go on, I am not sure I can help. I did test the plugin (2.1.6) with gradle 3.5 and was able to get it to work on my mac. 

What OS are you using? Not that createDmg uses the 'hdiutil' program which only exists on OSX, so if you are on a different OS it will not work. See the wiki for more info on this.

**Comment by crotwell** [comment]
Closing, assumed to be not run on Mac. Please reopen if you have more information.
