### ISSUE TITLE
About the dmg

### ISSUE THREAD

**Issue by yangwuan55** [crotwell/gradle-macappbundle#52]
I want create a dmg for drag app to the Applications dir,how can I do for this?
Thanks very much.

**Comment by crotwell** [comment]
Have you read the documentation on the wiki:
https://github.com/crotwell/gradle-macappbundle/wiki/Intro

Do you have a problem setting up the configuration or running `gradle createDmg`?

**Comment by yangwuan55** [comment]
I want like this...
![image](https://user-images.githubusercontent.com/5218120/32529103-48aec1f2-c3fc-11e7-8293-1ad415ec1561.png)

**Comment by crotwell** [comment]
Use a background image with your arrow like:
backgroundImage = "doc/macbackground.png"
the Applications folder will be liked as well.
Also you can use appIconX, appIconY, appFolderX, and appFolderY to position them. You may also need to manually set backgroundImageWidth and backgroundImageHeight if the window is not sized correctly.

I probably should separate those two steps so a background image can be used without also linking Applications, hopefully in the next version.

**Comment by yangwuan55** [comment]
Thanks!
I will try it.

**Comment by yangwuan55** [comment]
How to make the window height and width is current,I don't want the scrollbar.
Thanks very very much...
![image](https://user-images.githubusercontent.com/5218120/32707412-4a678830-c7e9-11e7-920e-2a869ef87809.png)

**Comment by crotwell** [comment]
The window should be sized to match the image, so try making the image larger.

Also, you may need to manually set backgroundImageWidth and backgroundImageHeight if the window is not sized correctly.

**Comment by yangwuan55** [comment]
OK,it works well.Thanks very.
