### ISSUE TITLE
Gradle 5.0 build fails on non-macOS systems

### ISSUE THREAD

**Issue by huxi** [crotwell/gradle-macappbundle#67]
Error message:
`> No value has been specified for property 'MacAppBundlePlugin jreHome'.`

`jreHome` is only actually required if `bundleJRE = true`. I was able to fix the build by setting `jreHome` to an arbitrary value.

See [this thread on the Gradle forum](https://discuss.gradle.org/t/gradle-5-0-rc-2-is-now-available-for-testing/29447/9?u=huxi).

**Comment by crotwell** [comment]
believe this is fixed in 52f098fc86ea9978506452fdd6b2ce6100857ff0 by setting jreHome to "" and making it optional property
